name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use a specific version compatible with your dependencies

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent remark-lint-emphasis-marker
          npx remark . --use remark-preset-lint-consistent --use remark-lint-emphasis-marker="*"
